### ISSUE TITLE
fade attribute of button is not documented

### ISSUE THREAD

**Issue by 271ch** [fomantic/Fomantic-UI-Docs#159]
In this example:
https://fomantic-ui.com/elements/button.html#animated
there is a `fade` class:

![image](https://user-images.githubusercontent.com/56249288/66859570-da17db80-ef8b-11e9-8c2f-2d5f846308fb.png)

but it seams to me that it is not documented on the same page.

**Comment by 271ch** [comment]
The same is for vertical. If I understand correctly fade and vertical are variants of animated. Why one is put on the left and the other on the right of animated? By changed or is it intended?

**Comment by lubber-de** [comment]
> The same is for vertical. If I understand correctly fade and vertical are variants of animated. Why one is put on the left and the other on the right of animated? By changed or is it intended?

For the current implementation of `animated button` the order of the classnames does not matter. (Also `ui animated vertical button` or even `button animated ui vertical` will work exactly the same )

I think it was just a pure spell reason, why the order differs in those examples:

"It's an animated fade button" sounds more correct than " It's an fade animated button"
"It's an vertical animated button" sounds more correct than " It's an animated vertical button"

I personally think the documentation is sufficient here, because the docs are expecting the user to look at the example HTML (as you did :wink:)  to find out the additional classnames for `animated` to achieve different results.

However, if you like, you are welcome to provide a PR with 2 more detailed examples for `vertical` and `fade`

**Comment by lubber-de** [comment]
Closing, as the docs are sufficient as commented above
