### ISSUE TITLE
getting started - link and script have incorrect paths

### ISSUE THREAD

**Issue by hkennyv** [fomantic/Fomantic-UI-Docs#227]
It seems like the following link has an incorrect href and the script has an incorrect src:

```
<link rel="stylesheet" type="text/css" href="/semantic/dist/semantic.min.css" />
<script src="/semantic/dist/semantic.min.js"></script>
```

You can see the errors in the console too:

```
semantic.min.css:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
semantic.min.js:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
```

Removing the leading "/" works for me and the styles are included as expected. im working on a PR for this to update the code snippet on this page: https://fomantic-ui.com/introduction/getting-started.html

:)

**fixed:**
```
<link rel="stylesheet" type="text/css" href="semantic/dist/semantic.min.css" />
<script src="semantic/dist/semantic.min.js"></script>
```

**Steps to reproduce:**
* create a new directory to test - `mkdir fui-test/`
* change into new directory - `cd fui-test/`
* initialize package.json - `npm init` (enter, enter, enter)
* install fomantic-ui (use automatic, default settings) - `npm install fomantic-ui`
* build fomantic-ui - `cd semantic && npx gulp build`
* create a sample html file - `touch index.html`

**index.html**
```html
<!DOCTYPE html>
<html>
  <head>
    <!-- You MUST include jQuery before Fomantic -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.3.1/dist/jquery.min.js"></script>
    <link rel="stylesheet" type="text/css" href="/semantic/dist/semantic.min.css">
    <script src="/semantic/dist/semantic.min.js"></script>
  </head>
  <body>
    <form class="ui form">
      <div class="field">
        <label>First Name</label>
        <input type="text" name="first-name" placeholder="First Name" />
      </div>
      <div class="field">
        <label>Last Name</label>
        <input type="text" name="last-name" placeholder="Last Name" />
      </div>
      <div class="field">
        <div class="ui checkbox">
          <input type="checkbox" tabindex="0" class="hidden" />
          <label>I agree to the Terms and Conditions</label>
        </div>
      </div>
      <button class="ui button" type="submit">Submit</button>
    </form>
  </body>
</html>
```

* open index.html in the browser and you should see the errors in the console

here's a sample branch i setup to view this: https://github.com/hkennyv/Fomantic-UI-Docs/tree/issue-sample/fuitest

**Comment by ko2in** [comment]
Hi, thank you for your contribution. Actually, this doesn't intend to include on that documentation page. It's just for demonstration how should the FUI CSS and JS include in your HTML project. The browser automatically trying to find the CSS and JS file, because the CSS and JS links are not encoded in the demonstration.

So, with or without forward slash, this will still return 404 because, this doesn't actually exist under `semantic` directory on doc [site](https://fomantic-ui.com/).

The correct solution should be encoding the HTML for `<link>` and `<script>` tags. Example:
```
&lt;link rel="stylesheet" type="text/css" href="/semantic/dist/semantic.min.css" /&gt;
&lt;script src="semantic/dist/semantic.min.js"&gt;&lt;/script&gt;
```

**Comment by ko2in** [comment]
Sorry for my incorrect conclusion about encoding issue. Please check my change request in your [PR](https://github.com/fomantic/Fomantic-UI-Docs/pull/228).

**Comment by hkennyv** [comment]
Thanks @ko2in , I think that there is a misunderstanding. I'm saying that there is an error in the instructions on the "getting started" page. If someone were to follow the instructions [here](https://fomantic-ui.com/introduction/getting-started.html), they will get the errors I listed above in the OP.

Please see my edited OP for the steps to reproduce and happy to answer any other questions!

**Comment by ko2in** [comment]
@hkennyv Thank you for your PR and sandbox. But, there's no misunderstanding. We don't have `semantic` directory on the doc [site](https://fomantic-ui.com).

So, `<link rel="stylesheet" type="text/css" href="/semantic/dist/semantic.min.css" />` and `<script src="/semantic/dist/semantic.min.js"></script>` would receive 404, with or without starting with a slash.

You're getting 404 error in getting started [page](https://fomantic-ui.com/introduction/getting-started.html) because of the following example:
![FUI-Getting-Started](https://user-images.githubusercontent.com/930315/92323231-05506100-f05d-11ea-8405-d1db64d88763.png)

Such example code blocks are generated by a script and it's sending the request for some reasons, and failed since there's no `semantic` directory on the doc site.

So, the [PR](https://github.com/fomantic/Fomantic-UI-Docs/pull/228#r483992263) you've submitted is correct and need some adjustments.
