### ISSUE TITLE
[Docs] Many behaviors are missing basic use syntax examples

### ISSUE THREAD

**Issue by designosis** [fomantic/Fomantic-UI-Docs#245]
The docs fail to provide proper syntax for how many of the behaviors should be called.

For example, the dropdown docs on https://fomantic-ui.com/modules/dropdown.html#/usage say ...

![Screen Shot 2020-11-25 at 12 11 12 PM](https://user-images.githubusercontent.com/146623/100260457-69294e00-2f17-11eb-889c-108fa19d7a49.png)

Then it mentions that you can clear a dropdown without triggering the onChange ...

![Screen Shot 2020-11-25 at 12 11 25 PM](https://user-images.githubusercontent.com/146623/100260477-6dee0200-2f17-11eb-8a7b-5f32e64955b8.png)

However it's entirely unclear as to how this is accomplished. How do you pass `preventChangeTrigger`? I've tried ...

```
$('#my_dropdown').dropdown('clear', true);
$('#my_dropdown').dropdown('clear(true)');
$('#my_dropdown').dropdown('clear', 'preventChangeTrigger', true);
$('#my_dropdown').dropdown('clear', {preventChangeTrigger: true});
```
All of them trigger the `onChange`. And this isn't just `dropdown`, it's everywhere in the docs.

I'd suggest the lack of example syntax is a critical problem found throughout the docs.

**Comment by ko2in** [comment]
The `preventChangeTrigger` is the argument name which will be passed as `argumentOne`. So you would have to use like below:
```
$('.ui.dropdown').dropdown('clear', true); // Prevent change trigger
$('.ui.dropdown').dropdown('clear', false); // Allow change trigger
```
You would have to check the type of argument for your behavior, in the above example: `clear` has only one argument and it's boolean. So, you just need to pass `true` or `false`.

Example for `show` behavior, it has two arguments `callback` which is function and `preventFocus` which is boolean. So, you just need to pass function and `true|false` after your behavior name as below:
```
$('.ui.dropdown').dropdown('show', function() { // Runs after showing dropdown }, true); // Trigger callback function and prevent focus
```

**Comment by neokio** [comment]
Yes, that's super clear, and should be in the docs :)

I posted this feature request because `$('.ui.dropdown').dropdown('clear', true);` wasn't working due to an unrelated issue (https://github.com/fomantic/Fomantic-UI/issues/1781) ... and in trying to understand why, I found the docs wording confusing, making me spend a lot of time trying to figure out whether or not I was doing it right.

It happens to me too often, where I read about behaviors with more complex arguments, and the behavior docs don't explain the actual syntax.

If there had been an example in the docs illustrating that `clear (preventChangeTrigger)` meant `clear` was the behavior and `preventChangeTrigger` was just an argument, and that the correct syntax was `$('.ui.dropdown).dropdown('clear', true);`, I would have found the error much sooner.

**Comment by ko2in** [comment]
Yes. I've talked about that in one issue in the past regarding the lacking example for module's behavior on the documentation page. We've also a [discussion](https://github.com/fomantic/Fomantic-UI-Docs/issues/218) about to integrate a live editor for each example which I think would help to get more familiar while reading the documentation.

**Comment by neokio** [comment]
Live editor! That's an exciting idea.

**Comment by lubber-de** [comment]
I think i can add a PR to at least move the arguments into a separate table column for better understanding
So instead of
|Behavior|Description|
|-|-|
|clear(preventChangeTrigger)|Clears dropdown of selection. Set preventChangeTrigger to true to omit the change event (default: false).|

it will become
|Behavior|arguments (name:type=default)|Description|
|-|-|-|
|clear|preventChangeTrigger: boolean = false|Clears dropdown of selection. Set preventChangeTrigger to true to omit the change event.|

@neokio Should be clear enough so far and fixes this issue?

A possible Live editor will be discussed in the [docs issue](https://github.com/fomantic/Fomantic-UI-Docs/issues/218) @ko2in mentioned above

**Comment by neokio** [comment]
The example provided is 

```
$('.your.element')
  .dropdown('behavior name', argumentOne, argumentTwo)
;
```

If the end result will be `$('#my_dropdown').dropdown('clear', false);`, then leading with `preventChangeTrigger`, which is never written by the end-user, adds confusion. It's should be perfect clear that you don't need to type it in anywhere!

Maybe it's good enough to just change the `Behavior` column from ...

Behavior | Description
-- | --
clear (preventChangeTrigger) |  Clears dropdown of selection. Set preventChangeTrigger to true to omit the change event (default: false).

... to ...

Behavior | Description
-- | --
clear, preventChangeTrigger |  Clears dropdown of selection. Set preventChangeTrigger to true to omit the change event (default: false).


 

I would also add at least one example using the most complex instance. In the case of dropdown, this line ...


Behavior | Description
-- | --
set value (value,text,$selected,preventChangeTrigger) | Sets dropdown input to value (does not update display state). text and $selected are used internally and can be ignored. Set preventChangeTrigger to true to omit the change event

**Comment by lubber-de** [comment]
> `$('#my_dropdown').dropdown('set value', , , true);`

Unfortunately yes . Infact the two arguments are only passed to the onchange trigger . For that particular behavior we had to be backward compatible when adding the preventChangeTrigger argument.
I admit this deserves a refactoring .

Then, to just make clear, that the names inside the parenthesis of the behavior table are the mentioned arguments (and reduce the amount of work to change the docs for now) how about just changing the Column header from `Behavior` to `Behavior (arguments)` ?
Behavior(argmuments) | Description
-- | --
clear (preventChangeTrigger) |  Clears dropdown of selection. Set preventChangeTrigger to true to omit the change event (default: false).

I think the main reason for the current docs since SUI was the idea that people will understand it's a function which usually gets its arguments inside parenthesis. By creating your issue, this is obviously not the case 🙂

**Comment by neokio** [comment]
> Then, to just make clear ... just changing the Column header from Behavior to Behavior (arguments) ...

Sure :) I think if there's a single example of the most complex case, like with `$('#my_dropdown').dropdown('set value', , , true);`, then that would be totally sufficient and clear. Without an example, I'd still be trying to figure out that `preventChangeTrigger` was a reference and didn't actually belong in the call.

**Comment by lubber-de** [comment]
Should be more clear now as discussed by #346
