### ISSUE TITLE
[fomantic-ui.com] Better searching on the fomantic-ui.com website on the icons page

### ISSUE THREAD

**Issue by arethk** [fomantic/Fomantic-UI-Docs#316]
Go to this link: https://fomantic-ui.com/elements/icon.html

With the browsers search feature, try searching for "folder". It shows 0 hits.

Go to the semantic version: https://semantic-ui.com/elements/icon.html

With the browsers search feature, try searching for "folder". It shows 26 hits.

I see the "Search icons ..." text box but I don't want to use that. It would be nice to be able to use the browser search and then see what other icons are related to my search. Thanks.

**Comment by exoego** [comment]
Hmm, searching "folder" on FUI shows many icons for me.

**Comment by exoego** [comment]
ah, browser search... sorry 🤭

**Comment by lubber-de** [comment]
Very strange.... CTRL+F only finds visible (scrolled into viewport) content altough there is no lazy loading , so the whole DOM is already existing 🤔

**Comment by lubber-de** [comment]
Found it, because of performance reasons (?) the following commit once implemented a feature to hide non visiible categories. Thereforce CTRL+F does not find them when not shown in the current viewport

https://github.com/fomantic/Fomantic-UI-Docs/commit/04193bd5a64f8df0a721fcb4a69c5953e95f75d0

@hammy2899 The only solution is see is to revert the particular `checkVisibility` codelogic, you once implemented. 
Opinon?

**Comment by lubber-de** [comment]
Fixed by #317
